// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LogMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from LogMessage.proto</summary>
public static partial class LogMessageReflection {

  #region Descriptor
  /// <summary>File descriptor for LogMessage.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static LogMessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBMb2dNZXNzYWdlLnByb3RvItoBCgpMb2dNZXNzYWdlEhQKDHNlcnZpY2Vf",
          "bmFtZRgBIAEoCRITCgt0ZWxlZ3JhbV9pZBgCIAEoCRITCgttZXRob2RfbmFt",
          "ZRgDIAEoCRImCghzZXZlcml0eRgEIAEoDjIULkxvZ01lc3NhZ2UuU2V2ZXJp",
          "dHkSDwoHbWVzc2FnZRgFIAEoCRIPCgdkZXRhaWxzGAYgASgJIkIKCFNldmVy",
          "aXR5EgkKBURlYnVnEAASCAoESW5mbxABEgsKB1dhcm5pbmcQAhIJCgVFcnJv",
          "chADEgkKBUZhdGFsEARiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::LogMessage), global::LogMessage.Parser, new[]{ "ServiceName", "TelegramId", "MethodName", "Severity", "Message", "Details" }, null, new[]{ typeof(global::LogMessage.Types.Severity) }, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class LogMessage : pb::IMessage<LogMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LogMessage> _parser = new pb::MessageParser<LogMessage>(() => new LogMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LogMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::LogMessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LogMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LogMessage(LogMessage other) : this() {
    serviceName_ = other.serviceName_;
    telegramId_ = other.telegramId_;
    methodName_ = other.methodName_;
    severity_ = other.severity_;
    message_ = other.message_;
    details_ = other.details_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LogMessage Clone() {
    return new LogMessage(this);
  }

  /// <summary>Field number for the "service_name" field.</summary>
  public const int ServiceNameFieldNumber = 1;
  private string serviceName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ServiceName {
    get { return serviceName_; }
    set {
      serviceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "telegram_id" field.</summary>
  public const int TelegramIdFieldNumber = 2;
  private string telegramId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string TelegramId {
    get { return telegramId_; }
    set {
      telegramId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "method_name" field.</summary>
  public const int MethodNameFieldNumber = 3;
  private string methodName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string MethodName {
    get { return methodName_; }
    set {
      methodName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "severity" field.</summary>
  public const int SeverityFieldNumber = 4;
  private global::LogMessage.Types.Severity severity_ = global::LogMessage.Types.Severity.Debug;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::LogMessage.Types.Severity Severity {
    get { return severity_; }
    set {
      severity_ = value;
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 5;
  private string message_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "details" field.</summary>
  public const int DetailsFieldNumber = 6;
  private string details_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Details {
    get { return details_; }
    set {
      details_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LogMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LogMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ServiceName != other.ServiceName) return false;
    if (TelegramId != other.TelegramId) return false;
    if (MethodName != other.MethodName) return false;
    if (Severity != other.Severity) return false;
    if (Message != other.Message) return false;
    if (Details != other.Details) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ServiceName.Length != 0) hash ^= ServiceName.GetHashCode();
    if (TelegramId.Length != 0) hash ^= TelegramId.GetHashCode();
    if (MethodName.Length != 0) hash ^= MethodName.GetHashCode();
    if (Severity != global::LogMessage.Types.Severity.Debug) hash ^= Severity.GetHashCode();
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    if (Details.Length != 0) hash ^= Details.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ServiceName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(ServiceName);
    }
    if (TelegramId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(TelegramId);
    }
    if (MethodName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(MethodName);
    }
    if (Severity != global::LogMessage.Types.Severity.Debug) {
      output.WriteRawTag(32);
      output.WriteEnum((int) Severity);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Message);
    }
    if (Details.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Details);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ServiceName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(ServiceName);
    }
    if (TelegramId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(TelegramId);
    }
    if (MethodName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(MethodName);
    }
    if (Severity != global::LogMessage.Types.Severity.Debug) {
      output.WriteRawTag(32);
      output.WriteEnum((int) Severity);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Message);
    }
    if (Details.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Details);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ServiceName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ServiceName);
    }
    if (TelegramId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TelegramId);
    }
    if (MethodName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MethodName);
    }
    if (Severity != global::LogMessage.Types.Severity.Debug) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Severity);
    }
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
    }
    if (Details.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Details);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LogMessage other) {
    if (other == null) {
      return;
    }
    if (other.ServiceName.Length != 0) {
      ServiceName = other.ServiceName;
    }
    if (other.TelegramId.Length != 0) {
      TelegramId = other.TelegramId;
    }
    if (other.MethodName.Length != 0) {
      MethodName = other.MethodName;
    }
    if (other.Severity != global::LogMessage.Types.Severity.Debug) {
      Severity = other.Severity;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    if (other.Details.Length != 0) {
      Details = other.Details;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ServiceName = input.ReadString();
          break;
        }
        case 18: {
          TelegramId = input.ReadString();
          break;
        }
        case 26: {
          MethodName = input.ReadString();
          break;
        }
        case 32: {
          Severity = (global::LogMessage.Types.Severity) input.ReadEnum();
          break;
        }
        case 42: {
          Message = input.ReadString();
          break;
        }
        case 50: {
          Details = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          ServiceName = input.ReadString();
          break;
        }
        case 18: {
          TelegramId = input.ReadString();
          break;
        }
        case 26: {
          MethodName = input.ReadString();
          break;
        }
        case 32: {
          Severity = (global::LogMessage.Types.Severity) input.ReadEnum();
          break;
        }
        case 42: {
          Message = input.ReadString();
          break;
        }
        case 50: {
          Details = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the LogMessage message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum Severity {
      [pbr::OriginalName("Debug")] Debug = 0,
      [pbr::OriginalName("Info")] Info = 1,
      [pbr::OriginalName("Warning")] Warning = 2,
      [pbr::OriginalName("Error")] Error = 3,
      [pbr::OriginalName("Fatal")] Fatal = 4,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
